services:
  # Serviço da API
  api:
    build:
      context: ..  # Define o diretório raiz como contexto de build
      dockerfile: docker/Dockerfile  # Especifica o Dockerfile para construir a imagem
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000  # Comando para iniciar o servidor FastAPI
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a porta 8000 do host
    env_file:
      - ../.env  # Carrega variáveis de ambiente do arquivo .env
    volumes:
      - ../data/chroma_db:/app/data/chroma_db  # Monta o diretório de dados no container
      - ../logs:/app/logs  # Monta o diretório de logs no container

  # Serviço do Bot
  bot:
    build:
      context: ..  # Define o diretório raiz como contexto de build
      dockerfile: docker/Dockerfile  # Especifica o Dockerfile para construir a imagem
    command: python app/bot.py  # Comando para executar o script do bot
    env_file:
      - ../.env  # Carrega variáveis de ambiente do arquivo .env
    depends_on:
      - api  # Garante que o serviço da API seja iniciado antes do bot
    volumes:
      - ../data/chroma_db:/app/data/chroma_db  # Monta o diretório de dados no container
      - ../logs:/app/logs  # Monta o diretório de logs no container