FROM python:3.9-slim

WORKDIR /app

# Copia apenas os arquivos necessários
COPY ./app ./app

RUN pip install --no-cache-dir \
    fastapi==0.95.2 \
    uvicorn==0.22.0 \
    python-dotenv==1.0.0 \
    httpx==0.24.1 \
    psutil==5.9.5

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8080"]