# Usa a mesma imagem base Python 3.9 slim
FROM python:3.9-slim

# Define o mesmo diretório de trabalho
WORKDIR /app

# Copia a pasta app
COPY app ./app

# Copia a pasta chat, ignorando a pasta test
COPY chat ./chat
RUN find ./chat -type d -name "test" -exec rm -rf {} + || true

# Copia a pasta app
COPY chroma_db ./chroma_db

# Se você tiver um requirements.txt, pode usá-lo assim:
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Comando para iniciar a aplicação
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8080"]