# Usa a mesma imagem base Python 3.9 slim
FROM python:3.9-slim

# Define o mesmo diretório de trabalho
WORKDIR /app

# Copia apenas a pasta app (otimização para construção em camadas)
COPY app ./app

# Instala as dependências específicas da API
RUN pip install --no-cache-dir \
    fastapi==0.95.2 \
    uvicorn==0.22.0 \
    python-dotenv==1.0.0 \
    httpx==0.24.1 \
    psutil==5.9.5

# Comando para iniciar a aplicação
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8080"]